name: /ota
on:
  issue_comment:
    types: [created]

jobs:
  main:
    name: Create ota commit
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ota')
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction to comment
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
      - name: Get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
      - name: Checkout upstream branch
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}
      - name: Create ota commit
        run: |
          git config user.name s2mr
          git config user.email s2mr@users.noreply.github.com
          HOGE="${{github.event.comment.body}} aaa"
          git commit --allow-empty -m "[ota] ${HOGE}"
          git push
