name: Create ota commit
on:
  issue_comment:
    types: [created]

jobs:
  test-job1:
    name: test job 1
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ota')
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Add reaction
        uses: actions/github-script@v5.1.0
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Checkout
        run: git checkout
      - name: Create ota commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout ${{ github.head_ref }}
          git commit --allow-empty -m "[ota]"
          git push
