name: Create ota commit
on:
  issue_comment:
    types: [created]

jobs:
  test-job1:
    name: test job 1
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/ota')
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: "rocket",
            });
      - name: get upstream branch
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.upstreambranch.outputs.branchname }}
      - name: Create ota commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --allow-empty -m "[ota]"
          git push
